import Head from 'next/head';
import { useEffect, useState } from 'react';
import styles from '../styles/Home.module.css';

import { useRouter } from "next/router";
import { SearchTodoInput, NewTaskButton, CreateTodoModal, TodoItemDetails  } from '../components';
import { useDispatch } from 'react-redux';
import { modalReducerAction } from '../src/store/actions';
import dynamic from 'next/dynamic';

const TodoList = dynamic(() => import('../components/TodoList/TodoList'), {ssr: false});

export default function Home() {
  const [ input, setInput ] = useState("");
  const dispatch = useDispatch();
  const router = useRouter();
  useEffect(() => {
    const storage = JSON.parse(localStorage.getItem('token'));
    if(!storage) {
      router.push("/auth")
    }
  })
  return (
    <>
      <Head>
        <title>Todos</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <CreateTodoModal/>
        <div className={styles.todo_container} >
          <SearchTodoInput
            value={input}
            placeholder='Search todo'
            onChange={(e) => setInput(e.target.value)}
          />
          <TodoList input={input} />
        </div>
        <div className={styles.btn_container} >
          <NewTaskButton 
            title='New Task' 
            onClick={() => dispatch(modalReducerAction())}
            />
        </div>
        <TodoItemDetails/>
      </main>
    </>
  )
}

// const { NEXT_PUBLIC_TODO_KEY, NEXT_PUBLIC_SITE_URL } = process.env

// export async function getServerSideProps() {

//   const {data} = await axios.post(`${NEXT_PUBLIC_SITE_URL}/api/get-todos`, {key: NEXT_PUBLIC_TODO_KEY});
//   return {
//     props: {
//       data
//     }
//   }
// }